from .sessions import RemediationCopilotSessionManager
from .reviews import build_copilot_review_packet
from .approvals import build_approval_request, evaluate_approval_scope
from .rehearsals import RehearsalManager
from .readiness import compute_execution_readiness
from .federation import build_portable_playbook_bundle
from .adaptation import adapt_portable_playbook_to_local_policy
from .automation_prep import build_automation_envelope, evaluate_self_healing_eligibility

from .contracts import CopilotApprovalRequestParams
